Fixing README.md file
Leonardo-Toledo-V/Instagram-clone pull request #2
Opened 2023-03-20 18:45 UTC by GJZ26

Is this the introductory documentation for Next.js or Instagram Clone??? smh

2023-03-20 18:48 UTC, GJZ26 commented on README.md
> -- `Feed`:
Aunque a veces es importante enlistar cosas, debes respetar la semántica de Markdown para facilitar la lectura

2023-03-21 01:43 UTC, Leonardo-Toledo-V commented on README.md
> -- `Feed`:
pinche mamón

2023-03-21 01:46 UTC, Leonardo-Toledo-V requested changes
Bro, I don't need anyone to tell me what to do in my repo, please don't talk to me.

2023-03-21 01:46 UTC, Leonardo-Toledo-V commented
Shut up bitch

2023-03-21 01:52 UTC, GJZ26 commented
> Bro, I don't need anyone to tell me what to do in my repo, please don't talk to me.

Accept my pull request, you bastard, mamahuevo

2023-03-21 01:58 UTC, merged

2023-03-21 23:05 UTC, GJZ26 commented on README.md
> -- `Feed`:
cálleseeee mamahuevoooo